import { v4 as uuid } from 'uuid'
import type { Trip } from '../types'

export function createSampleTrip(): Trip {
  return {
    id: uuid(),
    name: 'Europe Summer 2026',
    startDate: '2026-07-11',
    endDate: '2026-07-25',
    currency: 'AUD',
    settings: {
      airportBufferMinutes: 120,
      generalBufferMinutes: 15,
      trafficMultiplier: 1.15,
      averageSpeedKmh: 50,
    },
    stops: [
      {
        id: uuid(),
        name: 'Lucerne',
        location: 'Switzerland',
        arrivalDate: '2026-07-12',
        departureDate: '2026-07-18',
        notes: 'Base for Swiss Alps exploration',
      },
      {
        id: uuid(),
        name: 'Paris',
        location: 'France',
        arrivalDate: '2026-07-18',
        departureDate: '2026-07-25',
      },
    ],
    items: [
      {
        id: uuid(),
        type: 'flight',
        departureCity: 'Brisbane',
        arrivalCity: 'Lucerne',
        departureAirport: 'BNE — Brisbane Airport',
        arrivalAirport: 'ZRH — Zurich Airport',
        departureDateTime: '2026-07-11T05:00:00.000Z',
        arrivalDateTime: '2026-07-11T20:30:00.000Z',
        durationMinutes: 1230,
        airline: 'Qatar Airways',
        flightNumber: 'QR899 / QR95',
        connections: [
          { airport: 'DOH — Hamad International', layoverMinutes: 180 },
        ],
        departureLocation: 'Home — New Farm',
        departureDistanceKm: 12,
        cost: 2450,
        bookingReference: 'ABC123XYZ',
        notes: 'Window seat requested. 2×23kg baggage.',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'transport',
        mode: 'train',
        from: 'Zurich Airport',
        to: 'Lucerne Hauptbahnhof',
        dateTime: '2026-07-12T08:00:00.000Z',
        distanceKm: 52,
        durationMinutes: 55,
        cost: 28,
        notes: 'Direct train, buy at station',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'accommodation',
        name: 'Hotel Schweizerhof Luzern',
        address: 'Schweizerhofquai 3a, 6002 Luzern',
        checkIn: '2026-07-12T14:00:00.000Z',
        checkOut: '2026-07-18T10:00:00.000Z',
        nightlyRate: 320,
        cost: 1920,
        bookingReference: 'SCH-88421',
        notes: 'Lake view room, breakfast included',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'rental_car',
        company: 'Europcar',
        vehicleType: 'Compact SUV',
        pickupLocation: 'Lucerne Train Station',
        dropoffLocation: 'Lucerne Train Station',
        pickupDateTime: '2026-07-14T09:00:00.000Z',
        dropoffDateTime: '2026-07-17T18:00:00.000Z',
        dailyRate: 85,
        cost: 340,
        bookingReference: 'EU-556712',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'sightseeing',
        name: 'Mount Pilatus Golden Round Trip',
        location: 'Pilatus Kulm, Switzerland',
        startDateTime: '2026-07-15T08:30:00.000Z',
        endDateTime: '2026-07-15T16:00:00.000Z',
        ticketPrice: 89,
        openingHours: '8:30am – 5:00pm',
        bookingReference: 'PIL-2026-0715',
        notes: 'Cogwheel railway + cable car return',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'sightseeing',
        name: 'Chapel Bridge & Old Town Walk',
        location: 'Lucerne Old Town',
        startDateTime: '2026-07-13T10:00:00.000Z',
        endDateTime: '2026-07-13T13:00:00.000Z',
        ticketPrice: 0,
        openingHours: 'Always open',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'flight',
        departureCity: 'Zurich',
        arrivalCity: 'Paris',
        departureAirport: 'ZRH — Zurich Airport',
        arrivalAirport: 'CDG — Charles de Gaulle',
        departureDateTime: '2026-07-18T11:00:00.000Z',
        arrivalDateTime: '2026-07-18T12:15:00.000Z',
        durationMinutes: 75,
        airline: 'Swiss International',
        flightNumber: 'LX632',
        connections: [],
        departureLocation: 'Hotel Schweizerhof Luzern',
        departureDistanceKm: 65,
        cost: 185,
        bookingReference: 'LX-99821',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'accommodation',
        name: 'Le Marais Boutique Hotel',
        address: '12 Rue des Archives, 75004 Paris',
        checkIn: '2026-07-18T15:00:00.000Z',
        checkOut: '2026-07-25T10:00:00.000Z',
        nightlyRate: 280,
        cost: 1960,
        bookingReference: 'MAR-44102',
        attachments: [],
      },
      {
        id: uuid(),
        type: 'sightseeing',
        name: 'Louvre Museum',
        location: 'Rue de Rivoli, 75001 Paris',
        startDateTime: '2026-07-20T09:00:00.000Z',
        endDateTime: '2026-07-20T13:00:00.000Z',
        ticketPrice: 22,
        openingHours: '9:00am – 6:00pm (closed Tue)',
        bookingReference: 'LOU-TIMED-0920',
        notes: 'Timed entry 9:00am slot',
        attachments: [],
      },
    ],
  }
}

export function createEmptyTrip(): Trip {
  return {
    id: uuid(),
    name: 'My Holiday',
    startDate: new Date().toISOString().slice(0, 10),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    currency: 'AUD',
    settings: {
      airportBufferMinutes: 120,
      generalBufferMinutes: 15,
      trafficMultiplier: 1.0,
      averageSpeedKmh: 50,
    },
    stops: [],
    items: [],
  }
}
